### ISSUE TITLE
Go module support

### ISSUE THREAD

**Issue by onitake** [beevik/timerqueue#1]
Could you add Go module support?
Even if you're no longer working on timerqueue, this will make it easier and safer to use in other projects.

Also, the project is missing a license. Under what terms can it be used?
This will currently block its code and docs from being displayed on https://pkg.go.dev/github.com/beevik/timerqueue .

**Comment by brandond** [comment]
I would love to use this code as well, but unfortunately I cannot do so without a license. @beevik would you accept a PR to add a license of your choice?

**Comment by beevik** [comment]
go module support has been added. Sorry for taking so long to respond.
